_wandb:
    value:
        cli_version: 0.23.0
        e:
            hw4vjquasszwiqlfajsjx9cty6qpvdl3:
                codePath: src\main.py
                codePathLocal: src\main.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "1055864647680"
                        used: "959314173952"
                email: nour.khalaf031@eng-st.cu.edu.eg
                executable: C:\Users\nourh\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\python.exe
                git:
                    commit: 2724779dd1938cd2a19de5e25ef79e190d014b67
                    remote: https://github.com/nouraldeen1/RL-MBPO-Breakout.git
                gpu: NVIDIA GeForce GTX 1650
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1024
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1650
                      uuid: GPU-5d029924-30e3-e3f9-fcfa-19d235501804
                host: LAPTOP-51EDPAQO
                memory:
                    total: "34265485312"
                os: Windows-10-10.0.22631-SP0
                program: .\src\main.py
                python: CPython 3.8.10
                root: D:\as3b folder\CCE-C\term 5\rl\RL-last\RL-MBPO-Breakout
                startedAt: "2025-12-16T05:51:41.848343Z"
                writerId: hw4vjquasszwiqlfajsjx9cty6qpvdl3
        m: []
        python_version: 3.8.10
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 15
                - 16
                - 61
            "4": 3.8.10
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
algorithm:
    value: mbpo
ddqn:
    value:
        double_dqn: true
        epsilon_decay: 0.995
        epsilon_end: 0.01
        epsilon_start: 1
debug:
    value:
        action_debug_steps: 10000
        action_log_freq: 1000
early_stopping:
    value:
        enabled: false
        patience: 50000
        target_reward: 400
        window_size: 100
env:
    value:
        frame_size: 84
        frame_skip: 4
        frame_stack: 4
        name: BreakoutNoFrameskip-v4
        noop_max: 30
        num_envs: 4
        record_video: true
        video_dir: videos
        video_trigger_freq: 100
logging:
    value:
        checkpoint_dir: checkpoints
        log_freq: 1000
        save_freq: 100000
model:
    value:
        cnn_channels:
            - 32
            - 64
            - 64
        cnn_kernels:
            - 8
            - 4
            - 3
        cnn_strides:
            - 4
            - 2
            - 1
        dynamics_hidden_dim: 128
        ensemble_size: 3
        fc_dim: 256
        predict_reward: true
ppo:
    value:
        clip_range: 0.2
        ent_coef: 0.1
        gae_lambda: 0.95
        max_grad_norm: 0.5
        n_epochs: 10
        vf_coef: 0.5
sac:
    value:
        ent_coef: auto
        init_temperature: 0.2
        target_entropy: auto
seed:
    value: 42
training:
    value:
        batch_size: 64
        buffer_size: 100000
        dynamics_lr: "1e-4"
        gamma: 0.99
        gradient_steps: 1
        learning_starts: 20000
        model_rollout_batch_size: 256
        model_rollout_freq: 1000
        model_rollout_length: 1
        policy_lr: "1e-4"
        real_ratio: 0.5
        target_update_freq: 10000
        tau: 0.005
        total_timesteps: 100000
        train_freq: 4
wandb:
    value:
        enabled: true
        entity: null
        project: MBPO-Breakout
        tags:
            - mbpo
            - breakout
            - mbrl
